### ISSUE TITLE
What is the /v1/users/:id PUT api good for when you have v1/users/:id PATCH?

### ISSUE THREAD

**Issue by ozomer** [danielfsousa/express-rest-es2017-boilerplate#105]
Why do you need the user-controller `replace` function and the `/v1/users/:id` PUT api when you have the user-controller `update` function and the `/v1/users/:id` PATCH api?
Is this just for the example use-case (some people like to use PUT and some like to use PATCH), or is there some deeper reasoning behind this decision, like supporting some official api standard (i.e. OAuth)?

**Comment by danielfsousa** [comment]
It's just for example, they have different behaviors and you don't need both. Here is a good explanation: https://stackoverflow.com/a/28558968/4914054

**Comment by ozomer** [comment]
Thanks
