### ISSUE TITLE
calling errorHandler instead of next, in router.param userId

### ISSUE THREAD

**Issue by ozomer** [danielfsousa/express-rest-es2017-boilerplate#106]
The user controller `load` function calls the `errorHandler` directly instead of calling `next`:

https://github.com/danielfsousa/express-rest-es2017-boilerplate/blob/50b2992b620e06b2f3ea6112d3e3032066f9fd03/src/api/controllers/user.controller.js#L6-L18

This function is called by user router:
https://github.com/danielfsousa/express-rest-es2017-boilerplate/blob/50b2992b620e06b2f3ea6112d3e3032066f9fd03/src/api/routes/v1/user.route.js#L17

The [express-js example](https://expressjs.com/en/4x/api.html#router.param) calls `next(new Error('failed to load user'))` (their example shows how to handle a similar "user-loading" problem...).

**Comment by danielfsousa** [comment]
Exactly! We should let express propagate the error through the middlewares like the example above.

Do you want to submit a PR?

**Comment by ozomer** [comment]
So there was no mysterious reasoning behind the decision to call `errorHandler` instead of `next`?

**Comment by ozomer** [comment]
https://github.com/danielfsousa/express-rest-es2017-boilerplate/pull/115

**Comment by danielfsousa** [comment]
@ozomer Haha, No problem!

I really don't remember the reason why I decided to call errorHandler directly, I was just starting to learn node and express and I am almost sure it was a mistake.
