### ISSUE TITLE
Register new user with /auth/register doesn't handle duplicate email

### ISSUE THREAD

**Issue by gkatsanos** [danielfsousa/express-rest-es2017-boilerplate#12]
Hey Daniel,

In , `server/src/controllers/auth.controller.js` , it seems to me there's no check to see if the email exists already in the database.. (same check exists in user.controller.js)
```js
/**
 * Returns jwt token if registration was successful
 * @public
 */
exports.register = async (req, res, next) => {
  try {
    const user = await (new User(req.body)).save(); // check here?
    const userTransformed = user.transform();
    const token = generateTokenResponse(user, user.token());
    res.status(httpStatus.CREATED);
    return res.json({ token, user: userTransformed });
  } catch (error) {
    return next(User.checkDuplicateEmail(error));
  }
};
```

I am running a very similar implementation as your boilerplate and I get 
`POST http://localhost:3000/auth/register 409 (Conflict)` when I try to register with the same email. 

I guess what I'd like to understand is the difference between `auth.controller` and `user.controller` (are they doing different tasks, are they complementary or are they two different options for authentication?)

**Comment by gkatsanos** [comment]
OK, forget my issue, I just saw it's handled I just didn't handle it in my Frontend / Didn't see there was a return message :)

**Comment by danielfsousa** [comment]
I think it is just simpler and one less call to the database to let mongoose throw the error, I mean, that´s why we are using mongoose's model validation.

For creating users both auth.controller and user.controller are almost the same, the only difference is auth.controller returns a token and user.controller returns the user created. It is just a CRUD example to bootstrap your application, it could be anything else.
