### ISSUE TITLE
Issue in user tests with _.some()

### ISSUE THREAD

**Issue by asafbiton96** [danielfsousa/express-rest-es2017-boilerplate#128]
Hi,

In your tests you implement the following function:
```javascript
async function format(user) {
    const formated = user;
    // delete password
    delete formated.password;
    // get users from database
    const dbUser = (await User.findOne({ email: user.email })).transform();
    // remove null and undefined properties
    return omitBy(dbUser, isNil);
}
```

then you use it in `_.some()` to check if an object is included in `res.body`:
```javascript
const bran = format(dbUsers.branStark);
const john = format(dbUsers.jonSnow);

const includesBranStark = some(res.body, bran);
const includesjonSnow = some(res.body, john);
```

Since `format()` is an async function, it returns a `Promise`, and when used as a predicate in `_.some()`, **it will *always* return true**, which makes the test incorrect.

**Comment by danielfsousa** [comment]
That's right, I forgot to `await` the Promise. Do you want to submit a PR?

**Comment by danielfsousa** [comment]
Opening for [hacktoberfest](https://hacktoberfest.digitalocean.com/).
