### ISSUE TITLE
Send password reset emails

### ISSUE THREAD

**Issue by danielfsousa** [danielfsousa/express-rest-es2017-boilerplate#2]

**Comment by awojtczyk** [comment]
@danielfsousa How do you want to handle email sending? I can make PR with sendgrid, but it's not the best way i guess :)

**Comment by danielfsousa** [comment]
I just wanted to give an example of the flow. Something like this:

1. An endpoint that checks if the email exists, then generates a url with a token that has an expitation time and send it by email to the user
2. Another endpoint that receives the token and the new password, changes the password, invalidate the token and send another email informing that the password has been changed.

Sendgrid is good option for sending the email!

@awojtczyk What do you think of this flow?

**Comment by awojtczyk** [comment]
@danielfsousa exactly what I thought. I'll create PR in the next week.

**Comment by danielfsousa** [comment]
@awojtczyk ok, Thank you! 😃

**Comment by rudolph2907** [comment]
@awojtczyk did you manage to work on this. I can maybe have a squiz at it.

**Comment by DenisRupp** [comment]
@danielfsousa I can do it using nodemailer and handlebar for templates with partials, like mail header and footer. If it's ok for you I'll create PR as soon as possible.

**Comment by danielfsousa** [comment]
@rudolph2907 Well, @awojtczyk didn't reply, so I think you can pick this one

**Comment by rudolph2907** [comment]
@danielfsousa do we want to go straight with sendgrid, maybe rather something like node-mailer that can work with multiple providers?

**Comment by danielfsousa** [comment]
> @danielfsousa do we want to go straight with sendgrid, maybe rather something like node-mailer that can work with multiple providers?

@rudolph2907  `node-mailer` is a good option!

**Comment by danielfsousa** [comment]
Opening for [hacktoberfest](https://hacktoberfest.digitalocean.com/).

**Comment by blnk-space** [comment]
@danielfsousa I have already implemented this in one of my projects based on this boilerplate, let me know if I should make a PR for it

**Comment by danielfsousa** [comment]
Great! Feel free to open a PR.

Em qua, 2 de out de 2019 03:35, blnk-space <notifications@github.com>
escreveu:

**Comment by travislang** [comment]
Added a PR [here](https://github.com/danielfsousa/express-rest-es2017-boilerplate/pull/224) for this
