### ISSUE TITLE
Best way to run command line tasks

### ISSUE THREAD

**Issue by lardissone** [danielfsousa/express-rest-es2017-boilerplate#25]
I would like to run several tasks in the server like cron or manually executed ones (like creating a super user after first install), how do you suggest to implement it? 

I prefer not to deal with API calls directly since most of the commands runs on bash one liners (like a cron command).

**Comment by danielfsousa** [comment]
Why don't you ssh into the virtual machine and run a custom npm command?

I would create and API if some other app needs to communicate with it, but for manually executed scripts I set some custom npm scripts in the package.json.

There is one npm hook 'postinstall' that you could use in your example: https://docs.npmjs.com/misc/scripts

**Comment by lardissone** [comment]
Ah great, forgot about the `postinstall` hook. Thanks!
