### ISSUE TITLE
Question about the res.end following a res.json in your error handler

### ISSUE THREAD

**Issue by Boboss74** [danielfsousa/express-rest-es2017-boilerplate#27]
https://github.com/danielfsousa/express-rest-es2017-boilerplate/blob/e66d3be772040e3ecb3aff28e9fad6f8c8f28bcf/src/api/middlewares/error.js#L10-L25

Hi, I just wanna know why you add a `res.end()` after a `res.json()`

This is a kind of secure trick when responding in an error handler?

**Comment by danielfsousa** [comment]
No, It is not a secure trick, `res.end()` comes from the Node.js Core and `res.json()` already calls it.

Honestly, I don't remember why I added a `res.end()`, I was just starting to learn express, so that's a mistake.
