### ISSUE TITLE
User creation and permissions - Readme?

### ISSUE THREAD

**Issue by potatowave** [danielfsousa/express-rest-es2017-boilerplate#30]
I'm creating an API for a mobile app and would like to know the logic behind the currently implemented user model. 

I'd like to know a little bit more about the intended user registration flow of the boilerplate code. 

From my perspective I have two options:

1. Create an admin user for the mobile app to be able to create users. (Then I'd have to store some credentials on the mobile device, not ideal)
2. Make the registration endpoint public and allow users to create themselves.

**Comment by danielfsousa** [comment]
The user's endpoints of the boilerplate are just an example.

In an API for a mobile app you should make the registration endpoint public, so anyone can register.

The flow is simple:

1. User send email and password
2. You try to save the user credentials into the database
3. The pre-save event of mongoose is triggered, so it can hash the password before saving into the database for security reasons
4. The api generates a JWT access token and returns it

**Comment by buralex** [comment]
user model in this example allows saving duplicates emails, is it normal?

**Comment by buralex** [comment]
user model allows saving duplicates emails, is it normal?

**Comment by awojtczyk** [comment]
src/api/user/controller.js:
```javascript
export const create = ({ bodymen: { body } }, res, next) =>
  User.create(body)
    .then((user) => user.view(true))
    .then(success(res, 201))
    .catch((err) => {
      /* istanbul ignore else */
      if (err.name === 'MongoError' && err.code === 11000) {
        res.status(409).json({
          valid: false,
          param: 'email',
          message: 'Email taken'
        })
      } else {
        next(err)
      }
    })
```

src/api/user/index.js:

```javascript
router.post('/',
  body({ email, password, name, picture, role }),
  create)
```

Should be enough.
