### ISSUE TITLE
Can get it to run

### ISSUE THREAD

**Issue by reachdevelopers** [danielfsousa/express-rest-es2017-boilerplate#32]
`yarn dev v0.15.1
$ "nodemon ./src/index.js" 
sh: 1: nodemon ./src/index.js: not found
error Command failed with exit code 127.
`

**Comment by danielfsousa** [comment]
Did you install first?

`yarn`

**Comment by reachdevelopers** [comment]
Yes I have Yarn installed global.

**Comment by danielfsousa** [comment]
You should install the project's dependencies running `yarn` before `yarn dev`. 
Have you done this?
