### ISSUE TITLE
Explanation for the auth middleware ?

### ISSUE THREAD

**Issue by tusharf5** [danielfsousa/express-rest-es2017-boilerplate#46]
First of all thanks for an amazing repo. It is one of the most useful repos out there for express.

I was going through the structure of it and the only thing I couldn't completely understand was the flow of auth middleware with respect to user roles.

This part basically.
This is the [link](https://github.com/danielfsousa/express-rest-es2017-boilerplate/blob/master/src/api/middlewares/auth.js) to the whole file.

```javascript
  const logIn = Promise.promisify(req.logIn);
  const apiError = new APIError({
    message: error ? error.message : 'Unauthorized',
    status: httpStatus.UNAUTHORIZED,
    stack: error ? error.stack : undefined,
  });

  try {
    if (error || !user) throw error;
    await logIn(user, { session: false });
  } catch (e) {
    return next(apiError);
  }

  if (roles === LOGGED_USER) {
    if (user.role !== 'admin' && req.params.userId !== user._id.toString()) {
      apiError.status = httpStatus.FORBIDDEN;
      apiError.message = 'Forbidden';
      return next(apiError);
    }
  } else if (!roles.includes(user.role)) {
    apiError.status = httpStatus.FORBIDDEN;
    apiError.message = 'Forbidden';
    return next(apiError);
  } else if (err || !user) {
    return next(apiError);
  }

  req.user = user;
```

**Comment by danielfsousa** [comment]
Thank you, @tusharf5!

The purpose of this middleware is to check if the user has the role that you specified in the router file.

The logic of the LOGGED_USER is weird, my programming skills wasn't that good back then, sorry about that. But I will try to explain what I did: 

If the user is an admin, then he can access everything, if he is not an admin then the param of the url should contain his id, so he can't access other users info.

In production I recommend you to use a known and tested library to handle the authorization part of the api, maybe one of those should help you:

https://www.npmjs.com/package/accesscontrol
https://www.npmjs.com/package/express-jwt-permissions
https://www.npmjs.com/package/connect-roles

**Comment by tusharf5** [comment]
@danielfsousa Thanks for replying. We're using an implementation of access control that is very tightly coupled with our business Logic (which I think is not good :D ). I'll surely submit a PR if we come up with a more generic solution since we partially used your repository as the base of our app 👍 .
