### ISSUE TITLE
Docker deployment

### ISSUE THREAD

**Issue by nueldev** [danielfsousa/express-rest-es2017-boilerplate#55]
Hi.
I'm currently looking to deploy the dockerized container to my server.
I cloned the repo, cd to the directory, `yarn`, `cp .env.example .env` and started the docker container with `yarn docker:dev` but it says NODE_ENV is missing from my .env file but I double checked and it exists, any ideas? Could you try to reproduce so I could see if the issue is only on my side.

**Comment by danielfsousa** [comment]
https://github.com/danielfsousa/express-rest-es2017-boilerplate/commit/bebb141689a9fe4e6cfbcb513f1ecd78325d1df3 should fix this
