### ISSUE TITLE
Translate Joi validation messages

### ISSUE THREAD

**Issue by diegomr86** [danielfsousa/express-rest-es2017-boilerplate#72]
Hi, how can I translate all the Joi validation messages to another language like pt_BR?

**Comment by rudolph2907** [comment]
I found this post, that might be helpful: https://medium.com/@Yuschick/building-custom-localised-error-messages-with-joi-4a348d8cc2ba

**Comment by miladr0** [comment]
why language for Error text is not English, how can i changed back to english
```
"code": 400,
    "message": "Erro de Validação",
```

**Comment by miladr0** [comment]
> why language for Error text is not English, how can i chang back to english
> 
> ```
> "code": 400,
>     "message": "Erro de Validação",
> ```

Fount it, https://github.com/danielfsousa/express-rest-es2017-boilerplate/blob/032a005deaa68a06f476432f4d602917609a251a/src/api/middlewares/error.js#L36

**Comment by danielfsousa** [comment]
> > why language for Error text is not English, how can i chang back to english
> > ```
> > "code": 400,
> >     "message": "Erro de Validação",
> > ```
> 
> Fount it,
> 
> https://github.com/danielfsousa/express-rest-es2017-boilerplate/blob/032a005deaa68a06f476432f4d602917609a251a/src/api/middlewares/error.js#L36

Fixed https://github.com/danielfsousa/express-rest-es2017-boilerplate/commit/969def89878a0b59701695938f6889592b99e107
