### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by johndifini** [danielfsousa/express-rest-es2017-boilerplate#75]
Hi @danielfsousa 

Thanks for all your hard work on the REST Boilerplate.  I used it as the basis for my company's API.  I also used it as example content for my blog post about creating API documentation using Squarespace.  Here is the [blog post](https://selfaware.blog/home/2018/6/23/api-documentation), and here is the [boilerplate API reference](https://selfaware.blog/api-doc/).  If you'd like, I could clean up the reference so that you can reference it on your README.  Just let me know.

Regards,

John

**Comment by karx** [comment]
@johndifini The links seem to be down. Could you please check.

**Comment by johndifini** [comment]
Hmm... both links seems to be working for me.  I wonder if Squarespace was down when you tried.  Will you please try again when you get a chance?  Thanks.
https://selfaware.blog/home/2018/6/23/api-documentation
https://selfaware.blog/api-doc/

**Comment by karx** [comment]
My bad. Must be something on my home pc. Able to access it now.

**Comment by danielfsousa** [comment]
Hi @johndifini!

Thank you for the reference.
I've included your blog post in the README: https://github.com/danielfsousa/express-rest-es2017-boilerplate/commit/38d2e43208bbfe38c9adb4000b37d08f9b2de222

**Comment by johndifini** [comment]
Thanks, Daniel.  If you would like any changes to the documentation, just
let me know.

Regards,

John DiFini
