### ISSUE TITLE
Is there any hosting that supports Node 7+ ? 

### ISSUE THREAD

**Issue by gkatsanos** [danielfsousa/express-rest-es2017-boilerplate#8]
Hey, I was just trying to run the tests and noticed async fails because I am running Node 6.x on my system.
I noticed you mention 7.x+ as requirements but before upgrading I went on to see if there's any hosting provider covering the newest Node versions and to my surprise several only support 4.x or max 6.x .. (like AWS for example)
How hard would be to re-write the parts of the boilerplate needed for >6.x node? (I imagine async/await)

**Comment by danielfsousa** [comment]
You don't need to re-write, in fact you can run node 8+ on any major VPS provider, I personally use [Digital Ocean](https://www.digitalocean.com/) and recommend it, they have great tutorials on how to configure your VPS to run node. Another good option is [Heroku](https://www.heroku.com/), you won't need to configure a VPS, it is the easier and faster option. 
Also the LTS (Long Term Support) version of node 8 will be released in October, will become the most used version of node

Take a look:

- [https://devcenter.heroku.com/articles/getting-started-with-nodejs](https://devcenter.heroku.com/articles/getting-started-with-nodejs)
- [https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04)
- [http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html)

But if you really need node 6.x you can use [Babel](https://babeljs.io/) to transpile it before starting the app

**Comment by gkatsanos** [comment]
Thanks, I was recommended Heroku / Digital Ocean shortly after my post. I'll stick with native node 7.x+ to be future-proof, my project is about learning anyway. Thank you!
